# Dynamic configuration for middleware
http:
  middlewares:
    # Security headers
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        customResponseHeaders:
          X-Powered-By: ""
          Server: ""

    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 200

    # Compression
    compression:
      compress: {}

    # CORS
    cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders: 
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowMethods:
          - "GET"
          - "POST" 
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "http://localhost:4200"
          - "http://localhost:4000"
          - "https://localhost"
        accessControlExposeHeaders:
          - "Content-Length"
          - "Content-Type"
        accessControlMaxAge: 100
        addVaryHeader: true